`timescale 1ns / 1ps

// Import AXI VIP basic package
import axi_vip_pkg::*;

// Import the exclusive package generated by AXI VIP in your Block Design
// Note: The name must match the Component Name generated by Vivado
import DTC2_7VIP_M_CTRL_0_pkg::*;
import DTC2_7VIP_S_MEM_0_pkg::*;

module DTC2_7_VIP_tb();

    // Declare signals connecting to the DUT
    bit clk_100MHz;
    bit reset_n_rtl;
    wire o_irq;

    // Generate 100MHz Clock (Period 10ns)
    always #5 clk_100MHz = ~clk_100MHz;

    // Instantiate Wrapper (DUT)
    DTC2_7VIP_wrapper DUT (
        .clk_100MHz(clk_100MHz),
        .o_irq(o_irq),
        .reset_n_rtl(reset_n_rtl)
    );

    // Declare AXI VIP Agents
    // mst_t is used for Master, slv_mem_t is used for Slave with Memory Model
    DTC2_7VIP_M_CTRL_0_mst_t     master_agent;
    DTC2_7VIP_S_MEM_0_slv_mem_t  slave_agent;

    xil_axi_ulong base_reg = 32'h00000000; // Base address of the register
    xil_axi_prot_t prot = 0;
    xil_axi_resp_t resp;

    bit[31:0] sanity_data;
    bit[31:0] input_data = 32'hDEADBEEF;        

    // Variables for Slave Memory Backdoor Access
    xil_axi_ulong mem_addr = 32'h80000000; // Adjust this base address according to your Address Editor
    bit [7:0] backdoor_wr_data[] = new[4];
    bit [7:0] backdoor_rd_data[] = new[4];

    initial begin
        // 1. Initialize signals
        clk_100MHz = 0;
        reset_n_rtl = 0;

        // 2. Create Agents
        // A correct low-level Interface hierarchy path must be given. The path format is usually:
        // <DUT_instance>.<BD_instance>.<VIP_instance>.inst.IF
        master_agent = new("master_agent", DUT.DTC2_7VIP_i.M_CTRL.inst.IF);
        slave_agent  = new("slave_agent",  DUT.DTC2_7VIP_i.S_MEM.inst.IF);

        // Set Verbosity to see detailed Transaction info during Debug (Optional)
        master_agent.set_verbosity(400);
        slave_agent.set_verbosity(400);

        // Configure Slave Memory Model address range to 64K (0x10000 bytes)
        slave_agent.mem_model.set_addr_range(mem_addr, mem_addr + 32'hFFFF);

        // 3. Start Agents
        master_agent.start_master();
        slave_agent.start_slave();

        // 4. Reset sequence
        #50;
        reset_n_rtl = 1; // Release Reset (Active Low)
        #50;

        $display("=================================================");
        $display(" System Reset Deasserted. AXI VIP Agents Started.");
        $display("=================================================");

        // =========================================================
        // Configure and utilize Slave Agent Memory Model (Backdoor Access)
        // =========================================================
        // Backdoor Write: Preload data into the Slave Memory Model (Byte array)
        backdoor_wr_data = '{8'hEF, 8'hBE, 8'hAD, 8'hDE}; // Little-Endian (corresponds to 32'hDEADBEEF)
        slave_agent.mem_model.backdoor_memory_write(mem_addr, backdoor_wr_data);
        $display("[Slave VIP] Backdoor write to mem_addr %08h completed.", mem_addr);

        // Backdoor Read: Verify memory content was written correctly
        slave_agent.mem_model.backdoor_memory_read(mem_addr, backdoor_rd_data);
        $display("[Slave VIP] Backdoor read from mem_addr %08h: 0x%02h%02h%02h%02h", 
                 mem_addr, backdoor_rd_data[3], backdoor_rd_data[2], backdoor_rd_data[1], backdoor_rd_data[0]);

        // 5. Write your test Transactions here
        // For example: Use Master Agent to write to a register (you need to define variables like addr, data, etc.)
        master_agent.AXI4LITE_WRITE_BURST(base_reg+32'h00000300, prot, input_data, resp);
        #10; // Wait for some time before the next transaction
        master_agent.AXI4LITE_READ_BURST(base_reg+32'h00000300, prot, sanity_data, resp);

        // End simulation after a period of execution
        #2000;
        $display("Simulation Finished.");
        $finish;
    end

endmodule