`timescale 1ns / 1ps

// Import AXI VIP basic package
import axi_vip_pkg::*;

// Import the exclusive package generated by AXI VIP in your Block Design
// Note: The name must match the Component Name generated by Vivado
import DTC2_7VIP_M_CTRL_0_pkg::*;
import DTC2_7VIP_S_MEM_0_pkg::*;

module DTC2_7_VIP_tb();

    // Declare signals connecting to the DUT
    bit clk_100MHz;
    bit reset_n_rtl;
    wire o_irq;

    // Generate 100MHz Clock (Period 10ns)
    always #5 clk_100MHz = ~clk_100MHz;

    // Instantiate Wrapper (DUT)
    DTC2_7VIP_wrapper DUT (
        .clk_100MHz(clk_100MHz),
        .o_irq(o_irq),
        .reset_n_rtl(reset_n_rtl)
    );

    // Declare AXI VIP Agents
    // mst_t is used for Master, slv_mem_t is used for Slave with Memory Model
    DTC2_7VIP_M_CTRL_0_mst_t     master_agent;
    DTC2_7VIP_S_MEM_0_slv_mem_t  slave_agent;

    // Include Slave Memory Stimulus utility tasks
    `include "DTC2_7_VIP_slv_mem_stimulus.svh"

    xil_axi_ulong base_reg = 32'h00000000; // Base address of the register
    xil_axi_prot_t prot = 0;
    xil_axi_resp_t resp;

    bit[31:0] sanity_data;
    bit[31:0] input_data = 32'hDEADBEEF;        

    // Variables for Slave Memory Backdoor Access
    xil_axi_ulong mem_addr = 32'h80000000; // Adjust this base address according to your Address Editor
    bit [127:0] backdoor_wr_data;
    bit [15:0]  backdoor_wr_strb;
    bit [127:0] backdoor_rd_data;

    // ---------------------------------------------------------
    // Task for handling DMA interrupts
    // ---------------------------------------------------------
    task wait_for_rx_irq_and_clear;
        begin
            $display("[Master VIP] Waiting for o_irq (DMA rxn_done)...");
            wait(o_irq == 1'b1);
            $display("[Master VIP] Interrupt received! Clearing ISR...");
            // Write 1 to Clear (W1C) on CSR_ISR (0x18), bit 4 (RX Done)
            master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00000018, prot, 32'h0000_0010, resp);
            // Ensure o_irq is properly deasserted before proceeding to the next DMA phase
            #20; 
        end
    endtask

    initial begin
        // 1. Initialize signals
        clk_100MHz = 0;
        reset_n_rtl = 0;

        // 2. Create Agents
        master_agent = new("master_agent", DUT.DTC2_7VIP_i.M_CTRL.inst.IF);
        slave_agent  = new("slave_agent",  DUT.DTC2_7VIP_i.S_MEM.inst.IF);

        // Set Verbosity to see detailed Transaction info during Debug (Optional)
        master_agent.set_verbosity(400);
        slave_agent.set_verbosity(400);

        // Configure Slave Memory Model default value and fill policy
        set_mem_default_value_fixed(128'h0);

        // 3. Start Agents
        master_agent.start_master();
        slave_agent.start_slave();

        // 4. Reset sequence
        #200;
        reset_n_rtl = 1; // Release Reset (Active Low)
        #50;

        $display("=================================================");
        $display(" System Reset Deasserted. AXI VIP Agents Started.");
        $display("=================================================");

        // =========================================================
        // Configure and utilize Slave Agent Memory Model (Backdoor Access)
        // =========================================================
        backdoor_wr_data = 128'h000000000000000000000000DEADBEEF;
        backdoor_wr_strb = 16'hFFFF; // Enable all 16 bytes
        backdoor_mem_write(mem_addr, backdoor_wr_data, backdoor_wr_strb);
        $display("[Slave VIP] Backdoor write to mem_addr %08h completed.", mem_addr);

        backdoor_mem_read(mem_addr, backdoor_rd_data);
        $display("[Slave VIP] Backdoor read from mem_addr %08h: 0x%032h", mem_addr, backdoor_rd_data);


        // Load memory files
        // in home
        // load_mem_file_backdoor("C:/Users/gunda/Desktop/DTComplierv31/output_verification/instruction.mem", 32'h00000000);
        // load_mem_file_backdoor("C:/Users/gunda/Desktop/DTComplierv31/output_verification/input_act_L.mem", 32'h00010000);
        // load_mem_file_backdoor("C:/Users/gunda/Desktop/DTComplierv31/output_verification/input_act_H.mem", 32'h00010020);
        // load_mem_file_backdoor("C:/Users/gunda/Desktop/DTComplierv31/output_verification/input_wgt_L.mem", 32'h00010040);
        // load_mem_file_backdoor("C:/Users/gunda/Desktop/DTComplierv31/output_verification/input_wgt_H.mem", 32'h00010060);

        // in laptop
        load_mem_file_backdoor("C:/Users/Zenbear/Desktop/DTComplierv31/output_verification/instruction.mem", 32'h00000000);
        load_mem_file_backdoor("C:/Users/Zenbear/Desktop/DTComplierv31/output_verification/input_act_L.mem", 32'h00010000);
        load_mem_file_backdoor("C:/Users/Zenbear/Desktop/DTComplierv31/output_verification/input_act_H.mem", 32'h00010020);
        load_mem_file_backdoor("C:/Users/Zenbear/Desktop/DTComplierv31/output_verification/input_wgt_L.mem", 32'h00010040);
        load_mem_file_backdoor("C:/Users/Zenbear/Desktop/DTComplierv31/output_verification/input_wgt_H.mem", 32'h00010060);

        // in lab
        // load_mem_file_backdoor("/home/user/Allen/Desktop/DTComplierv31/output_verification/instruction.mem", 32'h00000000);
        // load_mem_file_backdoor("/home/user/Allen/Desktop/DTComplierv31/output_verification/input_act_L.mem", 32'h00010000);
        // load_mem_file_backdoor("/home/user/Allen/Desktop/DTComplierv31/output_verification/input_act_H.mem", 32'h00010020);
        // load_mem_file_backdoor("/home/user/Allen/Desktop/DTComplierv31/output_verification/input_wgt_L.mem", 32'h00010040);
        // load_mem_file_backdoor("/home/user/Allen/Desktop/DTComplierv31/output_verification/input_wgt_H.mem", 32'h00010060);

        // 1. System Reset & Init
        $display("[Master VIP] 1.1 Execute Software Reset");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00, prot, 32'h0000_0002, resp);
        #20;

        // Set Global RX Interrupt Enable once (CSR_IER bit 4)
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h1C,  prot, 32'h0000_0010, resp); 

        // 2. DMA Load Phase (Instructions and Data)
        // 2.1 Load Instructions to IFB
        $display("[Master VIP] 2.1 Load Instructions to IFB");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h310, prot, 32'h0000_0000, resp); // CSR_MS_R_ADDR_LO
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h314, prot, 32'h0000_0000, resp); // CSR_MS_R_ADDR_HI
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h318, prot, 32'h0000_0013, resp); // CSR_MS_R_LEN 
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00,  prot, 32'h0000_4080, resp); // Trigger DMA read
        $display("[Master VIP] Waiting for o_irq (DMA rxn_done)...");
        wait(o_irq == 1'b1);


        // 2.2 Load Data to IDB0
        $display("[Master VIP] 2.2 Load Data to IDB0");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h310, prot, 32'h0001_0000, resp); // CSR_MS_R_ADDR_LO
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h314, prot, 32'h0000_0000, resp); // CSR_MS_R_ADDR_HI
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h318, prot, 32'h0000_0002, resp); // CSR_MS_R_LEN
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00,  prot, 32'h0000_0080, resp); // Trigger DMA read
        $display("[Master VIP] Waiting for o_irq (DMA rxn_done)...");
        wait(o_irq == 1'b1);

        // 2.3 Load Data to IDB1
        $display("[Master VIP] 2.3 Load Data to IDB1");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h310, prot, 32'h0001_0020, resp); // CSR_MS_R_ADDR_LO
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h314, prot, 32'h0000_0000, resp); // CSR_MS_R_ADDR_HI
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h318, prot, 32'h0000_0002, resp); // CSR_MS_R_LEN
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00,  prot, 32'h0000_8080, resp); // Trigger DMA read
        $display("[Master VIP] Waiting for o_irq (DMA rxn_done)...");
        wait(o_irq == 1'b1);

        // 2.4 Load Data to IDB2
        $display("[Master VIP] 2.4 Load Data to IDB2");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h310, prot, 32'h0001_0040, resp); // CSR_MS_R_ADDR_LO
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h314, prot, 32'h0000_0000, resp); // CSR_MS_R_ADDR_HI
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h318, prot, 32'h0000_0002, resp); // CSR_MS_R_LEN
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00,  prot, 32'h0001_0080, resp); // Trigger DMA read
        $display("[Master VIP] Waiting for o_irq (DMA rxn_done)...");
        wait(o_irq == 1'b1);

        // 2.5 Load Data to IDB3
        $display("[Master VIP] 2.5 Load Data to IDB3");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h310, prot, 32'h0001_0060, resp); // CSR_MS_R_ADDR_LO
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h314, prot, 32'h0000_0000, resp); // CSR_MS_R_ADDR_HI
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h318, prot, 32'h0000_0002, resp); // CSR_MS_R_LEN
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00,  prot, 32'h0001_8080, resp); // Trigger DMA read
        $display("[Master VIP] Waiting for o_irq (DMA rxn_done)...");
        wait(o_irq == 1'b1);
        #100;

        // 3. Core Enable & Execution
        $display("[Master VIP] 3.1 Start Core Execution");
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00, prot, 32'h0000_0009, resp);
        #10;
        master_agent.AXI4LITE_WRITE_BURST(base_reg + 32'h00, prot, 32'h0000_0101, resp);

        // Note: Core Idle does not map to a dedicated bit in CSR_ISR, so polling is still used here.
        $display("[Master VIP] 3.2 Polling Core Status for Idle...");
        do begin
            master_agent.AXI4LITE_READ_BURST(base_reg + 32'h04, prot, sanity_data, resp); // Read CSR_STATUS_CORE_0
            #10;
        end while ((sanity_data & 32'h0000_0001) == 0); // Check if Bit 0 (core_idle) is 1
        
        $display("[Master VIP] Core execution completed!");

        // End simulation after a period of execution
        #2000;
        $display("Simulation Finished.");
        $finish;
    end

endmodule
